use std::rc::Rc;
use crate::{
    Name, Unit, Value, 
    dice::{Die, Face}, 
    units::DNumUnit };

pub fn build() -> (Rc<dyn Unit>, Vec<Rc<Die>>) {
    let unit: Rc<dyn Unit> = DNumUnit::new();
    let faces = faces(&unit);
    let dice = vec![
        Die::new("d2", faces[0..2].to_vec()),
        Die::new("d3", faces[0..3].to_vec()),
        Die::new("d4", faces[0..4].to_vec()),
        Die::new("d6", faces[0..6].to_vec()),
        Die::new("d8", faces[0..8].to_vec()),
        Die::new("d10", faces[0..10].to_vec()),
        Die::new("d12", faces[0..12].to_vec()),
        Die::new("d20", faces[0..20].to_vec()),
        Die::new("d30", faces[0..30].to_vec()),
        Die::new("d50", faces[0..50].to_vec()),
        Die::new("d100", faces[0..100].to_vec())];
    (unit, dice) }

fn name(name: &str) -> Name { Name::new(name).unwrap() }

fn faces(unit: &Rc<dyn Unit>) -> Vec<Rc<Face>> {
    vec![
        Face::with_one_val(name("1"), Value::new(unit, 1)),
        Face::with_one_val(name("2"), Value::new(unit, 2)),
        Face::with_one_val(name("3"), Value::new(unit, 3)),
        Face::with_one_val(name("4"), Value::new(unit, 4)),
        Face::with_one_val(name("5"), Value::new(unit, 5)),
        Face::with_one_val(name("6"), Value::new(unit, 6)),
        Face::with_one_val(name("7"), Value::new(unit, 7)),
        Face::with_one_val(name("8"), Value::new(unit, 8)),
        Face::with_one_val(name("9"), Value::new(unit, 9)),
        Face::with_one_val(name("10"), Value::new(unit, 10)),
        Face::with_one_val(name("11"), Value::new(unit, 11)),
        Face::with_one_val(name("12"), Value::new(unit, 12)),
        Face::with_one_val(name("13"), Value::new(unit, 13)),
        Face::with_one_val(name("14"), Value::new(unit, 14)),
        Face::with_one_val(name("15"), Value::new(unit, 15)),
        Face::with_one_val(name("16"), Value::new(unit, 16)),
        Face::with_one_val(name("17"), Value::new(unit, 17)),
        Face::with_one_val(name("18"), Value::new(unit, 18)),
        Face::with_one_val(name("19"), Value::new(unit, 19)),
        Face::with_one_val(name("20"), Value::new(unit, 20)),
        Face::with_one_val(name("21"), Value::new(unit, 21)),
        Face::with_one_val(name("22"), Value::new(unit, 22)),
        Face::with_one_val(name("23"), Value::new(unit, 23)),
        Face::with_one_val(name("24"), Value::new(unit, 24)),
        Face::with_one_val(name("25"), Value::new(unit, 25)),
        Face::with_one_val(name("26"), Value::new(unit, 26)),
        Face::with_one_val(name("27"), Value::new(unit, 27)),
        Face::with_one_val(name("28"), Value::new(unit, 28)),
        Face::with_one_val(name("29"), Value::new(unit, 29)),
        Face::with_one_val(name("30"), Value::new(unit, 30)),
        Face::with_one_val(name("31"), Value::new(unit, 31)),
        Face::with_one_val(name("32"), Value::new(unit, 32)),
        Face::with_one_val(name("33"), Value::new(unit, 33)),
        Face::with_one_val(name("34"), Value::new(unit, 34)),
        Face::with_one_val(name("35"), Value::new(unit, 35)),
        Face::with_one_val(name("36"), Value::new(unit, 36)),
        Face::with_one_val(name("37"), Value::new(unit, 37)),
        Face::with_one_val(name("38"), Value::new(unit, 38)),
        Face::with_one_val(name("39"), Value::new(unit, 39)),
        Face::with_one_val(name("40"), Value::new(unit, 40)),
        Face::with_one_val(name("41"), Value::new(unit, 41)),
        Face::with_one_val(name("42"), Value::new(unit, 42)),
        Face::with_one_val(name("43"), Value::new(unit, 43)),
        Face::with_one_val(name("44"), Value::new(unit, 44)),
        Face::with_one_val(name("45"), Value::new(unit, 45)),
        Face::with_one_val(name("46"), Value::new(unit, 46)),
        Face::with_one_val(name("47"), Value::new(unit, 47)),
        Face::with_one_val(name("48"), Value::new(unit, 48)),
        Face::with_one_val(name("49"), Value::new(unit, 49)),
        Face::with_one_val(name("50"), Value::new(unit, 50)),
        Face::with_one_val(name("51"), Value::new(unit, 51)),
        Face::with_one_val(name("52"), Value::new(unit, 52)),
        Face::with_one_val(name("53"), Value::new(unit, 53)),
        Face::with_one_val(name("54"), Value::new(unit, 54)),
        Face::with_one_val(name("55"), Value::new(unit, 55)),
        Face::with_one_val(name("56"), Value::new(unit, 56)),
        Face::with_one_val(name("57"), Value::new(unit, 57)),
        Face::with_one_val(name("58"), Value::new(unit, 58)),
        Face::with_one_val(name("59"), Value::new(unit, 59)),
        Face::with_one_val(name("60"), Value::new(unit, 60)),
        Face::with_one_val(name("61"), Value::new(unit, 61)),
        Face::with_one_val(name("62"), Value::new(unit, 62)),
        Face::with_one_val(name("63"), Value::new(unit, 63)),
        Face::with_one_val(name("64"), Value::new(unit, 64)),
        Face::with_one_val(name("65"), Value::new(unit, 65)),
        Face::with_one_val(name("66"), Value::new(unit, 66)),
        Face::with_one_val(name("67"), Value::new(unit, 67)),
        Face::with_one_val(name("68"), Value::new(unit, 68)),
        Face::with_one_val(name("69"), Value::new(unit, 69)),
        Face::with_one_val(name("70"), Value::new(unit, 70)),
        Face::with_one_val(name("71"), Value::new(unit, 71)),
        Face::with_one_val(name("72"), Value::new(unit, 27)),
        Face::with_one_val(name("73"), Value::new(unit, 37)),
        Face::with_one_val(name("74"), Value::new(unit, 47)),
        Face::with_one_val(name("75"), Value::new(unit, 57)),
        Face::with_one_val(name("76"), Value::new(unit, 67)),
        Face::with_one_val(name("77"), Value::new(unit, 77)),
        Face::with_one_val(name("78"), Value::new(unit, 87)),
        Face::with_one_val(name("79"), Value::new(unit, 97)),
        Face::with_one_val(name("80"), Value::new(unit, 80)),
        Face::with_one_val(name("81"), Value::new(unit, 81)),
        Face::with_one_val(name("82"), Value::new(unit, 82)),
        Face::with_one_val(name("83"), Value::new(unit, 83)),
        Face::with_one_val(name("84"), Value::new(unit, 84)),
        Face::with_one_val(name("85"), Value::new(unit, 85)),
        Face::with_one_val(name("86"), Value::new(unit, 86)),
        Face::with_one_val(name("87"), Value::new(unit, 87)),
        Face::with_one_val(name("88"), Value::new(unit, 88)),
        Face::with_one_val(name("89"), Value::new(unit, 89)),
        Face::with_one_val(name("90"), Value::new(unit, 90)),
        Face::with_one_val(name("91"), Value::new(unit, 91)),
        Face::with_one_val(name("92"), Value::new(unit, 92)),
        Face::with_one_val(name("93"), Value::new(unit, 93)),
        Face::with_one_val(name("94"), Value::new(unit, 94)),
        Face::with_one_val(name("95"), Value::new(unit, 95)),
        Face::with_one_val(name("96"), Value::new(unit, 96)),
        Face::with_one_val(name("97"), Value::new(unit, 97)),
        Face::with_one_val(name("98"), Value::new(unit, 98)),
        Face::with_one_val(name("99"), Value::new(unit, 99)),
        Face::with_one_val(name("100"), Value::new(unit, 100)),
    ]
}