use std::rc::Rc;
use crate::{Value, dice::{Die, Face}, units::DNumUnit, Unit};

pub fn build() -> (Rc<dyn Unit>, Vec<Rc<Die>>) {
    let unit: Rc<dyn Unit> = DNumUnit::new();
    let faces = faces(&unit);
    let dice = vec![
        Die::new("d2", faces[0..2].iter().collect()),
        Die::new("d3", faces[0..3].iter().collect()),
        Die::new("d4", faces[0..4].iter().collect()),
        Die::new("d6", faces[0..6].iter().collect()),
        Die::new("d8", faces[0..8].iter().collect()),
        Die::new("d10", faces[0..10].iter().collect()),
        Die::new("d12", faces[0..12].iter().collect()),
        Die::new("d20", faces[0..20].iter().collect()),
        Die::new("d30", faces[0..30].iter().collect()),
        Die::new("d50", faces[0..50].iter().collect()),
        Die::new("d100", faces[0..100].iter().collect())];
    (unit, dice) }

fn faces(unit: &Rc<dyn Unit>) -> Vec<Rc<Face>> {
    vec![
        Face::with_one_val("1", Value::new(unit, 1)),
        Face::with_one_val("2", Value::new(unit, 2)),
        Face::with_one_val("3", Value::new(unit, 3)),
        Face::with_one_val("4", Value::new(unit, 4)),
        Face::with_one_val("5", Value::new(unit, 5)),
        Face::with_one_val("6", Value::new(unit, 6)),
        Face::with_one_val("7", Value::new(unit, 7)),
        Face::with_one_val("8", Value::new(unit, 8)),
        Face::with_one_val("9", Value::new(unit, 9)),
        Face::with_one_val("10", Value::new(unit, 10)),
        Face::with_one_val("11", Value::new(unit, 11)),
        Face::with_one_val("12", Value::new(unit, 12)),
        Face::with_one_val("13", Value::new(unit, 13)),
        Face::with_one_val("14", Value::new(unit, 14)),
        Face::with_one_val("15", Value::new(unit, 15)),
        Face::with_one_val("16", Value::new(unit, 16)),
        Face::with_one_val("17", Value::new(unit, 17)),
        Face::with_one_val("18", Value::new(unit, 18)),
        Face::with_one_val("19", Value::new(unit, 19)),
        Face::with_one_val("20", Value::new(unit, 20)),
        Face::with_one_val("21", Value::new(unit, 21)),
        Face::with_one_val("22", Value::new(unit, 22)),
        Face::with_one_val("23", Value::new(unit, 23)),
        Face::with_one_val("24", Value::new(unit, 24)),
        Face::with_one_val("25", Value::new(unit, 25)),
        Face::with_one_val("26", Value::new(unit, 26)),
        Face::with_one_val("27", Value::new(unit, 27)),
        Face::with_one_val("28", Value::new(unit, 28)),
        Face::with_one_val("29", Value::new(unit, 29)),
        Face::with_one_val("30", Value::new(unit, 30)),
        Face::with_one_val("31", Value::new(unit, 31)),
        Face::with_one_val("32", Value::new(unit, 32)),
        Face::with_one_val("33", Value::new(unit, 33)),
        Face::with_one_val("34", Value::new(unit, 34)),
        Face::with_one_val("35", Value::new(unit, 35)),
        Face::with_one_val("36", Value::new(unit, 36)),
        Face::with_one_val("37", Value::new(unit, 37)),
        Face::with_one_val("38", Value::new(unit, 38)),
        Face::with_one_val("39", Value::new(unit, 39)),
        Face::with_one_val("40", Value::new(unit, 40)),
        Face::with_one_val("41", Value::new(unit, 41)),
        Face::with_one_val("42", Value::new(unit, 42)),
        Face::with_one_val("43", Value::new(unit, 43)),
        Face::with_one_val("44", Value::new(unit, 44)),
        Face::with_one_val("45", Value::new(unit, 45)),
        Face::with_one_val("46", Value::new(unit, 46)),
        Face::with_one_val("47", Value::new(unit, 47)),
        Face::with_one_val("48", Value::new(unit, 48)),
        Face::with_one_val("49", Value::new(unit, 49)),
        Face::with_one_val("50", Value::new(unit, 50)),
        Face::with_one_val("51", Value::new(unit, 51)),
        Face::with_one_val("52", Value::new(unit, 52)),
        Face::with_one_val("53", Value::new(unit, 53)),
        Face::with_one_val("54", Value::new(unit, 54)),
        Face::with_one_val("55", Value::new(unit, 55)),
        Face::with_one_val("56", Value::new(unit, 56)),
        Face::with_one_val("57", Value::new(unit, 57)),
        Face::with_one_val("58", Value::new(unit, 58)),
        Face::with_one_val("59", Value::new(unit, 59)),
        Face::with_one_val("60", Value::new(unit, 60)),
        Face::with_one_val("61", Value::new(unit, 61)),
        Face::with_one_val("62", Value::new(unit, 62)),
        Face::with_one_val("63", Value::new(unit, 63)),
        Face::with_one_val("64", Value::new(unit, 64)),
        Face::with_one_val("65", Value::new(unit, 65)),
        Face::with_one_val("66", Value::new(unit, 66)),
        Face::with_one_val("67", Value::new(unit, 67)),
        Face::with_one_val("68", Value::new(unit, 68)),
        Face::with_one_val("69", Value::new(unit, 69)),
        Face::with_one_val("70", Value::new(unit, 70)),
        Face::with_one_val("71", Value::new(unit, 71)),
        Face::with_one_val("72", Value::new(unit, 27)),
        Face::with_one_val("73", Value::new(unit, 37)),
        Face::with_one_val("74", Value::new(unit, 47)),
        Face::with_one_val("75", Value::new(unit, 57)),
        Face::with_one_val("76", Value::new(unit, 67)),
        Face::with_one_val("77", Value::new(unit, 77)),
        Face::with_one_val("78", Value::new(unit, 87)),
        Face::with_one_val("79", Value::new(unit, 97)),
        Face::with_one_val("80", Value::new(unit, 80)),
        Face::with_one_val("81", Value::new(unit, 81)),
        Face::with_one_val("82", Value::new(unit, 82)),
        Face::with_one_val("83", Value::new(unit, 83)),
        Face::with_one_val("84", Value::new(unit, 84)),
        Face::with_one_val("85", Value::new(unit, 85)),
        Face::with_one_val("86", Value::new(unit, 86)),
        Face::with_one_val("87", Value::new(unit, 87)),
        Face::with_one_val("88", Value::new(unit, 88)),
        Face::with_one_val("89", Value::new(unit, 89)),
        Face::with_one_val("90", Value::new(unit, 90)),
        Face::with_one_val("91", Value::new(unit, 91)),
        Face::with_one_val("92", Value::new(unit, 92)),
        Face::with_one_val("93", Value::new(unit, 93)),
        Face::with_one_val("94", Value::new(unit, 94)),
        Face::with_one_val("95", Value::new(unit, 95)),
        Face::with_one_val("96", Value::new(unit, 96)),
        Face::with_one_val("97", Value::new(unit, 97)),
        Face::with_one_val("98", Value::new(unit, 98)),
        Face::with_one_val("99", Value::new(unit, 99)),
        Face::with_one_val("100", Value::new(unit, 100)),
    ]
}