use std::rc::Rc;
use crate::{
    Value,
    dice::{Die, Face},
    units::DNumUnit};

pub fn build() -> Vec<Rc<Die>> {
    let faces = faces();
    vec![
        Die::new("d2".to_string(), faces[0..2].to_vec()),
        Die::new("d3".to_string(), faces[0..3].to_vec()),
        Die::new("d4".to_string(), faces[0..4].to_vec()),
        Die::new("d6".to_string(), faces[0..6].to_vec()),
        Die::new("d8".to_string(), faces[0..8].to_vec()),
        Die::new("d10".to_string(), faces[0..10].to_vec()),
        Die::new("d12".to_string(), faces[0..12].to_vec()),
        Die::new("d20".to_string(), faces[0..20].to_vec()),
        Die::new("d30".to_string(), faces[0..30].to_vec()),
        Die::new("d50".to_string(), faces[0..50].to_vec()),
        Die::new("d100".to_string(), faces[0..100].to_vec())] }

fn faces() -> Vec<Rc<Face>> {
    let relationship = DNumUnit::new();
    vec![
        Face::new("1".to_string(), vec![Value{ unit: relationship.clone(), value: 1}]),
        Face::new("2".to_string(), vec![Value{ unit: relationship.clone(), value: 2}]),
        Face::new("3".to_string(), vec![Value{ unit: relationship.clone(), value: 3}]),
        Face::new("4".to_string(), vec![Value{ unit: relationship.clone(), value: 4}]),
        Face::new("5".to_string(), vec![Value{ unit: relationship.clone(), value: 5}]),
        Face::new("6".to_string(), vec![Value{ unit: relationship.clone(), value: 6}]),
        Face::new("7".to_string(), vec![Value{ unit: relationship.clone(), value: 7}]),
        Face::new("8".to_string(), vec![Value{ unit: relationship.clone(), value: 8}]),
        Face::new("9".to_string(), vec![Value{ unit: relationship.clone(), value: 9}]),
        Face::new("10".to_string(), vec![Value{ unit: relationship.clone(), value: 10}]),
        Face::new("11".to_string(), vec![Value{ unit: relationship.clone(), value: 11}]),
        Face::new("12".to_string(), vec![Value{ unit: relationship.clone(), value: 12}]),
        Face::new("13".to_string(), vec![Value{ unit: relationship.clone(), value: 13}]),
        Face::new("14".to_string(), vec![Value{ unit: relationship.clone(), value: 14}]),
        Face::new("15".to_string(), vec![Value{ unit: relationship.clone(), value: 15}]),
        Face::new("16".to_string(), vec![Value{ unit: relationship.clone(), value: 16}]),
        Face::new("17".to_string(), vec![Value{ unit: relationship.clone(), value: 17}]),
        Face::new("18".to_string(), vec![Value{ unit: relationship.clone(), value: 18}]),
        Face::new("19".to_string(), vec![Value{ unit: relationship.clone(), value: 19}]),
        Face::new("20".to_string(), vec![Value{ unit: relationship.clone(), value: 20}]),
        Face::new("21".to_string(), vec![Value{ unit: relationship.clone(), value: 21}]),
        Face::new("22".to_string(), vec![Value{ unit: relationship.clone(), value: 22}]),
        Face::new("23".to_string(), vec![Value{ unit: relationship.clone(), value: 23}]),
        Face::new("24".to_string(), vec![Value{ unit: relationship.clone(), value: 24}]),
        Face::new("25".to_string(), vec![Value{ unit: relationship.clone(), value: 25}]),
        Face::new("26".to_string(), vec![Value{ unit: relationship.clone(), value: 26}]),
        Face::new("27".to_string(), vec![Value{ unit: relationship.clone(), value: 27}]),
        Face::new("28".to_string(), vec![Value{ unit: relationship.clone(), value: 28}]),
        Face::new("29".to_string(), vec![Value{ unit: relationship.clone(), value: 29}]),
        Face::new("30".to_string(), vec![Value{ unit: relationship.clone(), value: 30}]),
        Face::new("31".to_string(), vec![Value{ unit: relationship.clone(), value: 31}]),
        Face::new("32".to_string(), vec![Value{ unit: relationship.clone(), value: 32}]),
        Face::new("33".to_string(), vec![Value{ unit: relationship.clone(), value: 33}]),
        Face::new("34".to_string(), vec![Value{ unit: relationship.clone(), value: 34}]),
        Face::new("35".to_string(), vec![Value{ unit: relationship.clone(), value: 35}]),
        Face::new("36".to_string(), vec![Value{ unit: relationship.clone(), value: 36}]),
        Face::new("37".to_string(), vec![Value{ unit: relationship.clone(), value: 37}]),
        Face::new("38".to_string(), vec![Value{ unit: relationship.clone(), value: 38}]),
        Face::new("39".to_string(), vec![Value{ unit: relationship.clone(), value: 39}]),
        Face::new("40".to_string(), vec![Value{ unit: relationship.clone(), value: 40}]),
        Face::new("41".to_string(), vec![Value{ unit: relationship.clone(), value: 41}]),
        Face::new("42".to_string(), vec![Value{ unit: relationship.clone(), value: 42}]),
        Face::new("43".to_string(), vec![Value{ unit: relationship.clone(), value: 43}]),
        Face::new("44".to_string(), vec![Value{ unit: relationship.clone(), value: 44}]),
        Face::new("45".to_string(), vec![Value{ unit: relationship.clone(), value: 45}]),
        Face::new("46".to_string(), vec![Value{ unit: relationship.clone(), value: 46}]),
        Face::new("47".to_string(), vec![Value{ unit: relationship.clone(), value: 47}]),
        Face::new("48".to_string(), vec![Value{ unit: relationship.clone(), value: 48}]),
        Face::new("49".to_string(), vec![Value{ unit: relationship.clone(), value: 49}]),
        Face::new("50".to_string(), vec![Value{ unit: relationship.clone(), value: 50}]),
        Face::new("51".to_string(), vec![Value{ unit: relationship.clone(), value: 51}]),
        Face::new("52".to_string(), vec![Value{ unit: relationship.clone(), value: 52}]),
        Face::new("53".to_string(), vec![Value{ unit: relationship.clone(), value: 53}]),
        Face::new("54".to_string(), vec![Value{ unit: relationship.clone(), value: 54}]),
        Face::new("55".to_string(), vec![Value{ unit: relationship.clone(), value: 55}]),
        Face::new("56".to_string(), vec![Value{ unit: relationship.clone(), value: 56}]),
        Face::new("57".to_string(), vec![Value{ unit: relationship.clone(), value: 57}]),
        Face::new("58".to_string(), vec![Value{ unit: relationship.clone(), value: 58}]),
        Face::new("59".to_string(), vec![Value{ unit: relationship.clone(), value: 59}]),
        Face::new("60".to_string(), vec![Value{ unit: relationship.clone(), value: 60}]),
        Face::new("61".to_string(), vec![Value{ unit: relationship.clone(), value: 61}]),
        Face::new("62".to_string(), vec![Value{ unit: relationship.clone(), value: 62}]),
        Face::new("63".to_string(), vec![Value{ unit: relationship.clone(), value: 63}]),
        Face::new("64".to_string(), vec![Value{ unit: relationship.clone(), value: 64}]),
        Face::new("65".to_string(), vec![Value{ unit: relationship.clone(), value: 65}]),
        Face::new("66".to_string(), vec![Value{ unit: relationship.clone(), value: 66}]),
        Face::new("67".to_string(), vec![Value{ unit: relationship.clone(), value: 67}]),
        Face::new("68".to_string(), vec![Value{ unit: relationship.clone(), value: 68}]),
        Face::new("69".to_string(), vec![Value{ unit: relationship.clone(), value: 69}]),
        Face::new("70".to_string(), vec![Value{ unit: relationship.clone(), value: 70}]),
        Face::new("71".to_string(), vec![Value{ unit: relationship.clone(), value: 71}]),
        Face::new("72".to_string(), vec![Value{ unit: relationship.clone(), value: 27}]),
        Face::new("73".to_string(), vec![Value{ unit: relationship.clone(), value: 37}]),
        Face::new("74".to_string(), vec![Value{ unit: relationship.clone(), value: 47}]),
        Face::new("75".to_string(), vec![Value{ unit: relationship.clone(), value: 57}]),
        Face::new("76".to_string(), vec![Value{ unit: relationship.clone(), value: 67}]),
        Face::new("77".to_string(), vec![Value{ unit: relationship.clone(), value: 77}]),
        Face::new("78".to_string(), vec![Value{ unit: relationship.clone(), value: 87}]),
        Face::new("79".to_string(), vec![Value{ unit: relationship.clone(), value: 97}]),
        Face::new("80".to_string(), vec![Value{ unit: relationship.clone(), value: 80}]),
        Face::new("81".to_string(), vec![Value{ unit: relationship.clone(), value: 81}]),
        Face::new("82".to_string(), vec![Value{ unit: relationship.clone(), value: 82}]),
        Face::new("83".to_string(), vec![Value{ unit: relationship.clone(), value: 83}]),
        Face::new("84".to_string(), vec![Value{ unit: relationship.clone(), value: 84}]),
        Face::new("85".to_string(), vec![Value{ unit: relationship.clone(), value: 85}]),
        Face::new("86".to_string(), vec![Value{ unit: relationship.clone(), value: 86}]),
        Face::new("87".to_string(), vec![Value{ unit: relationship.clone(), value: 87}]),
        Face::new("88".to_string(), vec![Value{ unit: relationship.clone(), value: 88}]),
        Face::new("89".to_string(), vec![Value{ unit: relationship.clone(), value: 89}]),
        Face::new("90".to_string(), vec![Value{ unit: relationship.clone(), value: 90}]),
        Face::new("91".to_string(), vec![Value{ unit: relationship.clone(), value: 91}]),
        Face::new("92".to_string(), vec![Value{ unit: relationship.clone(), value: 92}]),
        Face::new("93".to_string(), vec![Value{ unit: relationship.clone(), value: 93}]),
        Face::new("94".to_string(), vec![Value{ unit: relationship.clone(), value: 94}]),
        Face::new("95".to_string(), vec![Value{ unit: relationship.clone(), value: 95}]),
        Face::new("96".to_string(), vec![Value{ unit: relationship.clone(), value: 96}]),
        Face::new("97".to_string(), vec![Value{ unit: relationship.clone(), value: 97}]),
        Face::new("98".to_string(), vec![Value{ unit: relationship.clone(), value: 98}]),
        Face::new("99".to_string(), vec![Value{ unit: relationship.clone(), value: 99}]),
        Face::new("100".to_string(), vec![Value{ unit: relationship.clone(), value: 100}]),
    ]
}